radar:
  id: 'intiaRadar'
  name: 'INTIA Method Radar'
  showName: true
  showAllSectorsText: 'Alle Sektoren'
  legendDropdownText: 'Legende'
  defaultColor: 'rgba(99, 110, 114, 1.0)'
  renderResolution: 410

sector:
  useColor: false
  showName: true
  nameOffset: 5

segment: 
  colorGradient: true
  colorGradientLimit: 1.66
  padding: 4

blip:
  size: 22
  defaultColor: '#8395a7'
  margin: 2